version: 0.2

phases:
  build:
    commands:
      # Your build commands here

      # Create a trigger file
      - echo "Trigger Lambda" > trigger.txt

      # Upload the trigger file to S3
      - aws s3 cp trigger.txt s3://lambdatrigger1/

artifacts:
  files: trigger.txt
