version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install pymysql

  build:
    commands:
      - git clone https://github.com/ZainHaiderPablo/sql_sample /tmp/repo
      - python /tmp/repo/SqlTrigger

artifacts:
  files: /tmp/repo/lambda_function.py
